[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
We have chosen to use the next technologies on the app:

* **React**: is a Javascript library focused on developing user interfaces so we decided to use it because of its big documentation and easy learning. It is also a solid base for creating apps with Javascript.

* **SOLID**: is an acronym that refers to five good and essential principles for the design of a software architecture (**S**ingle Responsibility, **O**pen/Closed, **L**iskov Substitution, **I**nterface Segregation and **D**ependency Inversion). With this principles the user knows that all his "sensitive data" is safe and decentralized. We use it because it is required on the project.

* **Node js**: is a Javascript execution environment controlled by events, what makes it light and efficient. It is also a nice option for reactive web apps because it's able to provide a big amount of simultaneous conections with high performance (big scalability). 

* *Javascript*: is an interpreted programming language based on prototypes, imperative and dynamic. We will use it on both frontend and backend.

* **CSS**: is a graphic programming language oriented to define the repesentation of a document. We will use it as part of the frontend of the app.

* **Docker**: is a software platform that allows to create, try and implement new apps easily and fast. We will use it for the fast deployment of our web application.

* **Netlify**: is a cloud server provider which we will use to deploy our app. It is also free (for our specific case) and it's one of the fastest options for deploying the app.

* **Github**: is a version management system where all the code will be stored, structured and modified.

* **Bootstrap**: is a framework that provides a collection of tools to simplify the use of html and css in the application.

=== Why this technologies?
* React, CSS, Javascript and NodeJS were chosen to reach a good level of usability and accesibility.
* Github was chosen for version control and organization and communication between the team.
* Bootstrap was chosen because the facilities it provides and to have a nice, clean and responsive view to the web app.
* Netlify was chosen because of its deployment, which it's very easy and it automaticaly builds when updating the app. 
