[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Register User
[plantuml,"register diagram",png]
----
actor User
entity EntityWeb as "WebApp"
database Pod as "USER_POD"

User -> EntityWeb: register
EntityWeb -> Pod: send user data 
Pod -> EntityWeb: notify success
EntityWeb -> User: log the user into the app
----


=== User Login Pod
[plantuml,"login diagram",png]
----
actor User
entity EntityWeb as "WebApp"
database Pod as "USER_POD"

User -> EntityWeb: enter WebID
EntityWeb -> Pod: send webId
Pod -> Pod: check login data
Pod -> EntityWeb: notify success
EntityWeb -> User: log the user into the app
----

=== Visualize map
[plantuml,"Map diagram",png]
----
actor User
entity EntityWeb as "WebApp"
database Pod as "USER_POD"

User -> EntityWeb: select the data to load on map
EntityWeb -> Pod: get locations
Pod --> EntityWeb: send data back
EntityWeb -> User: show map
----


=== Friends list
[plantuml,"Friends list diagram",png]
----
actor User
entity EntityWeb as "WebApp"
database Pod as "USER_POD"

User -> EntityWeb: select friend list option (has to be logged)
EntityWeb -> Pod: get friends data
Pod --> EntityWeb: send data back
EntityWeb -> User: show friends list
----

=== Add places to map
[plantuml,"Add places diagram",png]
----
actor User
entity EntityWeb as "WebApp"
database Pod as "USER_POD"

User -> EntityWeb: select a place on the map (has to be logged)
EntityWeb -> Pod: add place to pod
Pod -> EntityWeb: notify success
EntityWeb -> User: show new point on map
----


=== Reviews
[plantuml,"Reviews diagram",png]
----
actor User
entity EntityWeb as "WebApp"
database Pod as "USER_POD"

User -> EntityWeb: select a place on the map to review (has to be logged)
EntityWeb -> Pod: add review to place on user pod
Pod -> EntityWeb: notify success
EntityWeb -> User: show review on map
----

=== Filter map
[plantuml,"filter map diagram",png]
----
actor User
entity EntityWeb as "WebApp"

User -> EntityWeb: select a category (has to be logged)
EntityWeb -> EntityWeb: filter markers to specified category
EntityWeb -> User: show places for specified category on map
----

