[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

=== Risks
This is a list of identified technical risks, ordered by priority (1 is the highest priority).

1. Not knowing some of the technologies that we decided to use in this application. Such as SOLID (and PODs), REACT, AWS, OpenStreet Maps API or Docker. Some of us haven't worked with web applications either. 
* In order to avoid this risk or minimize its damage, we will have to learn how to use this technologies, having to spend some time to do it.

2. Due to having other projects and exams from other subjects, we will have limited time to work on this project that can lead to errors for rushing the project. 
* In order to avoid this risk or minimize its damage, we will have to plan well how we are going to do this project.

3. A member of the group could leave it or drop the subject, having to work the same with less members. 
* In order to avoid this risk or minimize its damage, we will have to quickly restructure the assignments to each member so the project can continue. We must avoid the bus factor.

4. Some of the members of the group didn't know each other before the project, this could lead to misunderstandings because we are not close enough to voice our concerns or ideas. 
* In order to avoid this risk or minimize its damage, we will have to be open to the other team members, always consider their ideas and help each other if someone doesn't understand something.

=== Technical Debt
This is a list of identified technical debts, ordered by priority (1 is the highest priority).

1. The frontend application unsolved package vulnerabilities, forcing us to use the '--force' when we need to install.